name = "cdn"
main = "src/index.ts"
compatibility_date = "2023-03-07"
send_metrics = false

account_id = "3d314ce955c4f69056e1f4b64842fd55"
workers_dev = false

routes = [
    "cdn.serenmodz.rocks/*",
    "cdn.ghosty.link/*",
    "cdn.demonyuto.link/*"
]

kv_namespaces = [
    { binding = "CDN_USERS", id = "913344d345d843299cd1107c52007924", preview_id = "c5d67610a03b481c8822f529d74ad7a1" }
]

[[r2_buckets]]
binding = "CDN_BUCKET"
bucket_name = "cdn"
preview_bucket_name = "cdn"

[vars]
REDIRECT_URL = "https://www.serenmodz.rocks"
